# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Run Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Xcode
      run: |
        xcodebuild clean test -project Ccommerce/Ccommerce.xcodeproj \
        -scheme CcommerceTest \
        -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest'
